package com.pencarimovie.downloader

import android.Manifest
import android.content.ComponentName
import android.content.Context
import android.content.Intent
import android.content.ServiceConnection
import android.content.pm.PackageManager
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.os.IBinder
import android.os.PowerManager
import android.provider.Settings
import android.view.View
import android.widget.LinearLayout
import android.widget.TextView
import android.widget.Toast
import androidx.appcompat.app.AlertDialog
import androidx.appcompat.app.AppCompatActivity
import androidx.core.app.ActivityCompat
import androidx.core.content.ContextCompat
import androidx.lifecycle.lifecycleScope
import com.google.android.material.button.MaterialButton
import com.google.android.material.dialog.MaterialAlertDialogBuilder
import kotlinx.coroutines.launch
import java.io.File

class MainActivity : AppCompatActivity() {

    companion object {
        private const val KEY_BACKGROUND_GUIDE_SHOWN = "background_guide_shown"
    }

    private var serverService: ServerService? = null
    private var isBound = false

    private lateinit var btnStartStop: MaterialButton
    private lateinit var btnOpenBrowser: MaterialButton
    private lateinit var btnBackgroundGuide: MaterialButton
    private lateinit var switchAutoStart: com.google.android.material.switchmaterial.SwitchMaterial
    private lateinit var switchBatterySaver: com.google.android.material.switchmaterial.SwitchMaterial
    private lateinit var tvStatus: TextView
    private lateinit var tvLog: TextView
    private lateinit var updateBanner: LinearLayout
    private lateinit var tvUpdateText: TextView
    private lateinit var btnUpdateDownload: MaterialButton
    private lateinit var updateProgress: android.widget.ProgressBar

    private var currentState: ServerState = ServerState.Idle
    private var serverPort: Int = 8088
    private var lanIp: String? = null

    /** Tracks the state observer registration, so we can remove it on disconnect. */
    private var stateObserver: ((ServerState) -> Unit)? = null

    /** Tracks the last appended log line to skip consecutive duplicates. */
    private var lastLogLine: String? = null

    /** True while an update APK is downloading, to block duplicate taps. */
    private var isDownloadingUpdate = false

    private val serviceConnection = object : ServiceConnection {
        override fun onServiceConnected(name: ComponentName?, service: IBinder?) {
            serverService = (service as? ServerService.LocalBinder)?.getService()
            // Remove any previous observer to prevent accumulation on re-bind
            val svc = serverService
            stateObserver?.let { svc?.state?.removeObserver(it) }
            // Register fresh observer
            stateObserver = { state ->
                runOnUiThread { onStateChanged(state) }
            }
            svc?.state?.observe(stateObserver!!)

            // Set up runtime log callback — receives ALL server process output
            // independently of server state. Structured JSON logs from
            // FrankenPHP/Caddy (internal diagnostics) are filtered out here.
            // Also skip lines that duplicate app-generated status messages
            // (Starting, Running, etc.) — these are no longer emitted by state
            // handlers, but the process may still output similar lines.
            svc?.onServerLogLine = { line ->
                runOnUiThread {
                    if (line.isNotBlank() &&
                        // Show structured JSON logs from FrankenPHP *only* if they
                        // contain user-relevant content (e.g., download requests).
                        // Pure internal diagnostics (tls, admin, heartbeat) are
                        // filtered out.
                        (!line.trimStart().startsWith("{") || line.contains("PencariMovie Server") || line.contains("PencariMovie Downloader")) &&
                        // Skip lines that duplicate app-generated status messages
                        // still emitted by updateUiForState() (Error, Stopping).
                        !line.startsWith("Stopping server") &&
                        !line.startsWith("Error:") &&
                        // Skip lines generated by the app itself
                        !line.startsWith("Server start requested") &&
                        !line.startsWith("Server stop requested") &&
                        !line.startsWith("Bootstrap installed")) {
                        // Skip consecutive duplicates (e.g., repeated heartbeat)
                        if (line == lastLogLine) return@runOnUiThread
                        lastLogLine = line
                        appendLog(line)
                    }
                }
            }

            // Sync battery saver state with the service
            val prefs = getSharedPreferences(BootReceiver.PREFS_NAME, Context.MODE_PRIVATE)
            svc?.setBatterySaver(prefs.getBoolean(ServerService.KEY_BATTERY_SAVER, true))
        }

        override fun onServiceDisconnected(name: ComponentName?) {
            serverService?.onServerLogLine = null
            stateObserver?.let { serverService?.state?.removeObserver(it) }
            stateObserver = null
            serverService = null
            isBound = false
        }
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        btnStartStop = findViewById(R.id.btnStartStop)
        btnOpenBrowser = findViewById(R.id.btnOpenBrowser)
        btnBackgroundGuide = findViewById(R.id.btnBackgroundGuide)
        switchAutoStart = findViewById(R.id.switchAutoStart)
        switchBatterySaver = findViewById(R.id.switchBatterySaver)
        tvStatus = findViewById(R.id.tvStatus)
        tvLog = findViewById(R.id.tvLog)
        updateBanner = findViewById(R.id.updateBanner)
        tvUpdateText = findViewById(R.id.tvUpdateText)
        btnUpdateDownload = findViewById(R.id.btnUpdateDownload)
        updateProgress = findViewById(R.id.updateProgress)

        btnBackgroundGuide.setOnClickListener {
            checkAndPromptBatteryOptimization(forcePrompt = true)
        }

        val prefs = getSharedPreferences(BootReceiver.PREFS_NAME, Context.MODE_PRIVATE)
        switchAutoStart.isChecked = prefs.getBoolean(BootReceiver.KEY_AUTO_START, false)
        switchAutoStart.setOnCheckedChangeListener { _, isChecked ->
            prefs.edit().putBoolean(BootReceiver.KEY_AUTO_START, isChecked).apply()
        }

        switchBatterySaver.isChecked = prefs.getBoolean(ServerService.KEY_BATTERY_SAVER, true)
        switchBatterySaver.setOnCheckedChangeListener { _, isChecked ->
            prefs.edit().putBoolean(ServerService.KEY_BATTERY_SAVER, isChecked).apply()
            serverService?.setBatterySaver(isChecked)
        }

        setupListeners()
        updateUiForState(ServerState.Idle)

        // Non-blocking update check — never delays startup, never blocks the UI.
        checkForAppUpdate()

        // Disable Start button until bootstrap check completes
        btnStartStop.isEnabled = false

        // Check and extract bootstrap on first launch (matches TermuxActivity.java pattern)
        val prefixDir = File(TermuxInstaller.PREFIX_DIR_PATH)
        val isFirstLaunch = !prefixDir.isDirectory || (prefixDir.list()?.isEmpty() == true)

        TermuxInstaller.setupBootstrapIfNeeded(this, Runnable {
            runOnUiThread {
                if (isFirstLaunch) {
                    appendLog("Bootstrap installed successfully")
                }
                btnStartStop.isEnabled = true
                // Show battery optimization dialog once on first install (only if not already exempt)
                if (isFirstLaunch) {
                    checkAndPromptBatteryOptimization()
                }
            }
        })
    }

    override fun onStart() {
        super.onStart()
        bindService()
    }

    override fun onStop() {
        super.onStop()
        if (isBound) {
            unbindService(serviceConnection)
            isBound = false
        }
    }

    private fun bindService() {
        val intent = Intent(this, ServerService::class.java)
        bindService(intent, serviceConnection, Context.BIND_AUTO_CREATE)
        isBound = true
    }

    private fun setupListeners() {
        btnStartStop.setOnClickListener {
            when (currentState) {
                is ServerState.Idle, is ServerState.Error -> {
                    requestNotificationPermissionAndStart()
                }
                is ServerState.Running -> {
                    stopServer()
                }
                else -> { /* ignore */ }
            }
        }

        btnOpenBrowser.setOnClickListener {
            val port = (currentState as? ServerState.Running)?.port
                ?: (serverService?.state?.value as? ServerState.Running)?.port
                ?: serverPort
            val host = "127.0.0.1"
            val url = "http://$host:$port"
            try {
                val intent = Intent(Intent.ACTION_VIEW, Uri.parse(url))
                startActivity(intent)
            } catch (e: Exception) {
                Toast.makeText(this, "No browser found to open $url", Toast.LENGTH_SHORT).show()
            }
        }
    }

    /**
     * Check the rolling `apk-latest` release for a newer APK and, if found,
     * reveal the update banner.
     *
     * Runs on [lifecycleScope] so it is cancelled automatically if the activity
     * is destroyed. Any failure (offline, rate-limited, malformed JSON) is
     * swallowed by [UpdateChecker] and simply leaves the banner hidden — an
     * update check must never interfere with starting the server.
     */
    private fun checkForAppUpdate() {
        lifecycleScope.launch {
            val info = UpdateChecker.checkForUpdate(BuildConfig.VERSION_CODE) ?: return@launch

            tvUpdateText.text = getString(
                R.string.update_available,
                info.versionName,
                BuildConfig.VERSION_NAME
            )
            updateBanner.visibility = View.VISIBLE

            btnUpdateDownload.setOnClickListener { downloadAndInstallUpdate(info) }
        }
    }

    /**
     * Download the update APK and hand it to the system package installer.
     *
     * Android always shows its own confirmation dialog before installing, so
     * this is never silent. If the download or hash check fails, fall back to
     * opening the release page so the user can install manually.
     */
    private fun downloadAndInstallUpdate(info: UpdateChecker.UpdateInfo) {
        // Guard against a second tap while a download is already running.
        if (isDownloadingUpdate) return
        isDownloadingUpdate = true
        btnUpdateDownload.isEnabled = false

        // Show the progress bar immediately so the tap has visible feedback
        // before the first byte arrives.
        updateProgress.visibility = View.VISIBLE
        updateProgress.isIndeterminate = true
        updateProgress.progress = 0
        btnUpdateDownload.text = getString(R.string.update_downloading)

        lifecycleScope.launch {
            try {
                val apk = UpdateChecker.downloadApk(this@MainActivity, info) { done, total ->
                    runOnUiThread {
                        if (total > 0) {
                            val pct = (done * 100 / total).toInt()
                            // Switch from spinner to determinate once we know
                            // the total size.
                            updateProgress.isIndeterminate = false
                            updateProgress.progress = pct
                            btnUpdateDownload.text =
                                getString(R.string.update_downloading_pct, pct)
                        } else {
                            updateProgress.isIndeterminate = true
                            btnUpdateDownload.text = getString(R.string.update_downloading)
                        }
                    }
                }

                if (apk == null) {
                    Toast.makeText(
                        this@MainActivity,
                        R.string.update_download_failed,
                        Toast.LENGTH_LONG
                    ).show()
                    openReleasePage()
                    return@launch
                }

                // Download done — hand off to the installer.
                updateProgress.isIndeterminate = true
                btnUpdateDownload.text = getString(R.string.update_installing)

                if (!UpdateChecker.installApk(this@MainActivity, apk)) {
                    Toast.makeText(
                        this@MainActivity,
                        R.string.update_install_failed,
                        Toast.LENGTH_LONG
                    ).show()
                    openReleasePage()
                }
            } finally {
                isDownloadingUpdate = false
                btnUpdateDownload.isEnabled = true
                btnUpdateDownload.text = getString(R.string.update_download)
                updateProgress.visibility = View.GONE
                updateProgress.isIndeterminate = false
            }
        }
    }

    private fun openReleasePage() {
        try {
            startActivity(Intent(Intent.ACTION_VIEW, Uri.parse(UpdateChecker.RELEASE_PAGE_URL)))
        } catch (e: Exception) {
            Toast.makeText(this, UpdateChecker.RELEASE_PAGE_URL, Toast.LENGTH_LONG).show()
        }
    }

    private fun onStateChanged(state: ServerState) {
        currentState = state
        when (state) {
            is ServerState.Running -> {
                serverPort = state.port
                lanIp = state.lanIp
            }
            else -> {}
        }
        updateUiForState(state)
    }

    private fun updateUiForState(state: ServerState) {
        when (state) {
            is ServerState.Idle -> {
                btnStartStop.text = "Start Server"
                btnStartStop.isEnabled = true
                btnOpenBrowser.isEnabled = false
                tvStatus.text = "Status: Idle"
                tvStatus.setTextColor(getColor(R.color.glass_text_dim))
                // Clear accumulated log on stop, so old sessions don't pile up
                tvLog.text = ""
            }
            is ServerState.Starting -> {
                btnStartStop.text = "Starting..."
                btnStartStop.isEnabled = false
                btnOpenBrowser.isEnabled = false
                tvStatus.text = "Status: Starting..."
                tvStatus.setTextColor(getColor(R.color.glass_warn))
                // Do NOT appendLog here — the process output (delivered via
                // onServerLogLine) will contain server startup messages. The
                // status bar above already shows "Starting..." visually.
            }
            is ServerState.SetupProgress -> {
                btnStartStop.text = "Starting..."
                btnStartStop.isEnabled = false
                btnOpenBrowser.isEnabled = false
                tvStatus.text = "Status: Setting up..."
                tvStatus.setTextColor(getColor(R.color.glass_warn))
                // Log output is delivered via onServerLogLine (set in
                // serviceConnection), which runs independently of state.
                // state.message is only used for the status text above.
            }
            is ServerState.Running -> {
                btnStartStop.text = "Stop Server"
                btnStartStop.isEnabled = true
                btnOpenBrowser.isEnabled = true
                val ipInfo = if (state.lanIp != null) "LAN: http://${state.lanIp}:${state.port}" else ""
                tvStatus.text = "Status: Running (port ${state.port})\n$ipInfo"
                tvStatus.setTextColor(getColor(R.color.glass_ok))
                // Do NOT appendLog here — the process output (delivered via
                // onServerLogLine) will contain "Server running on port..." and
                // "LAN access:..." messages. The status bar above already shows
                // the running state with IP info.
            }
            is ServerState.Error -> {
                btnStartStop.text = "Start Server"
                btnStartStop.isEnabled = true
                btnOpenBrowser.isEnabled = false
                tvStatus.text = "Status: Error"
                tvStatus.setTextColor(getColor(R.color.glass_error))
                // Keep appendLog for Error — the error message may not appear
                // in process output (e.g., exceptions from native runner).
                appendLog("Error: ${state.message}")
            }
            is ServerState.Stopping -> {
                btnStartStop.text = "Stopping..."
                btnStartStop.isEnabled = false
                btnOpenBrowser.isEnabled = false
                tvStatus.text = "Status: Stopping..."
                tvStatus.setTextColor(getColor(R.color.glass_error))
                // Keep appendLog for Stopping — the process won't output
                // "Stopping server..." since it's being killed externally.
                appendLog("Stopping server...")
            }
        }
    }

    private fun requestNotificationPermissionAndStart() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            if (ContextCompat.checkSelfPermission(this, Manifest.permission.POST_NOTIFICATIONS)
                != PackageManager.PERMISSION_GRANTED
            ) {
                ActivityCompat.requestPermissions(
                    this,
                    arrayOf(Manifest.permission.POST_NOTIFICATIONS),
                    100
                )
                return
            }
        }
        startServer()
    }

    override fun onRequestPermissionsResult(
        requestCode: Int,
        permissions: Array<out String>,
        grantResults: IntArray
    ) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults)
        if (requestCode == 100) {
            if (grantResults.isNotEmpty() && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
                startServer()
            } else {
                Toast.makeText(this, "Notification permission required for background server", Toast.LENGTH_LONG).show()
            }
        }
    }

    private fun startServer() {
        val intent = ServerService.startIntent(this)
        ContextCompat.startForegroundService(this, intent)
        appendLog("Server start requested")
    }

    private fun stopServer() {
        val intent = ServerService.stopIntent(this)
        startService(intent)
        appendLog("Server stop requested")
    }

    /**
     * Check if battery optimization is enabled and prompt the user to disable it.
     *
     * On most Android 6+ devices, battery optimization can prevent foreground
     * services from running reliably. OEMs like Xiaomi, Samsung, Huawei, and
     * OnePlus have especially aggressive background killing. This prompt guides
     * the user to the system settings to whitelist the app.
     *
     * Only shows once (checks [Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS]
     * directly rather than using a shared preference flag).
     */
    private fun openAppSettings() {
        try {
            val intent = Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS).apply {
                data = Uri.parse("package:$packageName")
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            }
            startActivity(intent)
        } catch (_: Exception) {
            try {
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                    val intent = Intent(
                        Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS,
                        Uri.parse("package:$packageName")
                    ).apply {
                        addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
                    }
                    startActivity(intent)
                }
            } catch (_: Exception) {}
        }
    }

    /**
     * Shows the background-activity / battery-exemption guide.
     *
     * The dialog is ALWAYS cancelable so the user is never locked out on any
     * Android version or OEM. When battery optimization is active, an extra
     * "Start Anyway" button lets the user proceed without changing settings.
     */
    private fun checkAndPromptBatteryOptimization(forcePrompt: Boolean = false) {
        val prefs = getSharedPreferences(BootReceiver.PREFS_NAME, Context.MODE_PRIVATE)
        if (!forcePrompt) {
            if (prefs.getBoolean(KEY_BACKGROUND_GUIDE_SHOWN, false)) return
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                val pm = getSystemService(Context.POWER_SERVICE) as? PowerManager
                if (pm?.isIgnoringBatteryOptimizations(packageName) == true) {
                    prefs.edit().putBoolean(KEY_BACKGROUND_GUIDE_SHOWN, true).apply()
                    return
                }
            }
        }
        prefs.edit().putBoolean(KEY_BACKGROUND_GUIDE_SHOWN, true).apply()

        val message = StringBuilder().apply {
            append("⚠️ IMPORTANT: Android may stop PencariMovie Server if background activity is restricted!\n\n")
            append("Recommended steps to keep the server running in the background:\n\n")
            append("1. Allow Background Activity:\n")
            append("   Allow the app to run in the background.\n\n")
            append("2. Lock in Recents App:\n")
            append("   Open the Recent Apps screen, long-press (or open the menu on) PencariMovie, and choose Lock (padlock/pin icon).\n\n")
            append("3. Battery > Unrestricted:\n")
            append("   Go to App Info > Battery / Battery usage > set to 'Unrestricted' / 'No restrictions', and turn OFF Smart mode / Optimized.\n")
            append("   (Samsung/Xiaomi/Oppo/Vivo users: also turn OFF 'Deep sleeping apps' and turn ON 'Auto-start' / 'Background launch').\n\n")
            append("4. Turn ON 'Auto start on boot' in the app:\n")
            append("   Enable the toggle inside this app so the server automatically restarts after the phone reboots.\n\n")
            append("5. Do NOT Swipe Clear:\n")
            append("   After locking in recents, keep the server notification active. Android kills background processes that have no foreground notification.\n\n")
            append("6. Check Cleaner / RAM Booster:\n")
            append("   If you use a cleaner or battery booster, exclude/whitelist PencariMovie from its clean list.")
        }.toString()

        MaterialAlertDialogBuilder(this)
            .setTitle("Keep Server Running in Background")
            .setMessage(message)
            .setCancelable(true)
            .setPositiveButton("Open Settings") { _, _ ->
                openAppSettings()
            }
            .setNegativeButton("Close", null)
            .show()
    }

    private fun appendLog(message: String) {
        tvLog.append("$message\n")
        // Auto-scroll to bottom — defer after layout pass to avoid NPE
        // when layout is null (called from onCreate before first layout pass)
        tvLog.post {
            val layout = tvLog.layout ?: return@post
            val scrollAmount = layout.getLineTop(tvLog.lineCount) - tvLog.height
            if (scrollAmount > 0) {
                tvLog.scrollTo(0, scrollAmount)
            }
        }
    }
}
